use axum::{Json, extract::State};
use serde::{Deserialize, Serialize};
use crate::{error::Result, state::AppState};

#[derive(Debug, Deserialize)]
pub struct ChallengeQuery {
	pub authority: String,
	pub signer_pubkey: String,
}

#[derive(Debug, Serialize)]
pub struct ChallengeResponse {
	pub nonce: String,
	pub expires_at: String,
}

pub async fn get_challenge(
	State(_state): State<AppState>,
) -> Result<Json<ChallengeResponse>> {
	todo!("issue nonce challenge for signer")
}

#[derive(Debug, Deserialize)]
pub struct CreateSessionRequest {
	/// Ephemeral public key generated by the client.
	pub ephemeral_pubkey: String,
	/// Nonce from the challenge.
	pub nonce: String,
	/// Attestation signature from canonical admin key over ephemeral_pubkey + authority + nonce.
	pub attestation_signature: String,
	pub signer_pubkey: String,
	pub authority: String,
}

#[derive(Debug, Serialize)]
pub struct SessionResponse {
	pub session_id: String,
	pub expires_at: String,
}

pub async fn create_session(
	State(_state): State<AppState>,
	Json(_body): Json<CreateSessionRequest>,
) -> Result<Json<SessionResponse>> {
	todo!("verify attestation against ASM signer set, create session")
}

pub async fn delete_session(
	State(_state): State<AppState>,
) -> Result<()> {
	todo!("invalidate session")
}
