use crate::{application::auth, error::Result, state::AppState};
use axum::{extract::State, Json};
use serde::{Deserialize, Serialize};

#[allow(dead_code)] // Planned: auth flow implementation
#[derive(Debug, Deserialize)]
pub struct ChallengeQuery {
    pub authority: String,
    pub signer_pubkey: String,
}

#[derive(Debug, Serialize)]
pub struct ChallengeResponse {
    pub nonce: String,
    pub expires_at: String,
}

pub async fn get_challenge(State(_state): State<AppState>) -> Result<Json<ChallengeResponse>> {
    let _challenge = auth::get_challenge("TODO", "TODO")?;
    todo!("map challenge to ChallengeResponse")
}

#[derive(Debug, Deserialize)]
pub struct CreateSessionRequest {
    /// Ephemeral public key generated by the client.
    pub ephemeral_pubkey: String,
    /// Nonce from the challenge.
    pub nonce: String,
    /// Attestation signature from canonical admin key over ephemeral_pubkey + authority + nonce.
    pub attestation_signature: String,
    pub signer_pubkey: String,
    pub authority: String,
}

#[derive(Debug, Serialize)]
pub struct SessionResponse {
    pub session_id: String,
    pub expires_at: String,
}

pub async fn create_session(
    State(_state): State<AppState>,
    Json(body): Json<CreateSessionRequest>,
) -> Result<Json<SessionResponse>> {
    let input = auth::CreateSessionInput {
        ephemeral_pubkey: body.ephemeral_pubkey,
        nonce: body.nonce,
        attestation_signature: body.attestation_signature,
        signer_pubkey: body.signer_pubkey,
        authority: body.authority,
    };
    let _result = auth::create_session(input)?;
    todo!("map session result to SessionResponse")
}

pub async fn delete_session(State(_state): State<AppState>) -> Result<()> {
    auth::delete_session("TODO")
}
